export const ADJECTIVES = {
  "혁신과 독창성": {
    창조적인: "creative",
    혁신적인: "innovative",
    독창적인: "original",
    참신한: "novel",
    독특한: "unique",
    차별화된: "differentiated",
    신선한: "refreshing",
    발전적인: "progressive",
    획기적인: "revolutionary",
    기발한: "whimsical",
    현대적인: "modern",
    웅장한: "magnificent",
  },
  "품질 및 전문성": {
    고품질의: "high-quality",
    전문적인: "professional",
    "신뢰할 수 있는": "trustworthy",
    "가성비의": "effective",
    숙련된: "expert",
    탁월한: "excellent",
    선도적인: "leading",
    최신식의: "streamlined",
    정확한: "accurate",
  },
  "고객 중심": {
    고객중심적인: "customer-centric",
    협력적인: "collaborative",
    참여적인: "engaging",
    "참여도가 높은": "participatory",
    친절한: "friendly",
    현실적인: "practical",
    쾌적한: "pleasant",
    공정한: "fair",
  },
  친환경적: {
    친환경적인: "eco-friendly",
    자연친화적인: "environmentally friendly",
  },
  효율성: {
    "효율적인": "efficient",
    유연한: "flexible",
    "융통성 있는": "adaptable",
    균형잡힌: "balanced",
    안전한: "safe",
    자율적인: "autonomous",
    편리한: "convenient",
    협조적인: "cooperative",
    빠른: "fast",
    신속한: "swift",
    최적의: "optimal",
    생산적인: "productive",
  },
};

export type ADJECTIVES_Type = typeof ADJECTIVES;
